

const desc = "Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus.Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus.Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus.Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus.Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus.Nullam id dolor id  ";



const DanielToran = "I am very excited to share with you our new quarterly digital newsletter. We've been working tirelessly on many exciting projects, and it’s high time we found a better way to share our successes and updates with each and every one of you. This is where this newsletter idea was born. On a quarterly basis, we want to celebrate the remarkable achievements within our digital landscape, from the amazing strides made by our oodi team to the latest innovations in our digital services, eSports ventures, and our portfolio of outstanding Zain apps. But it doesn't end there. We want this newsletter to be more than just a source of updates. It's an opportunity for all of us to become digital natives, equipped with the knowledge and resources necessary to thrive in the digital era. Digital transformation isn't limited to a single department—it encompasses every one of us at Zain. By uniting our efforts, breaking down silos, and fostering a culture of innovation, we can push boundaries and achieve even greater heights.   ";
const AliAliZahid = "In today's fast-paced world, where connectivity and communication are more important than ever, we find ourselves at the forefront of shaping the digital future. Our mission to connect people, businesses, and communities through cutting-edge technology is not only impactful but also essential.It is your talent and relentless pursuit of excellence that enables us to deliver superior services, bridging gaps and empowering individuals and organizations. Digitalization presents vast opportunities for growth, innovation, and superior customer experiences.By adopting digital technologies, we can optimize efficiency, streamline operations, and tap into new revenue streams.To that end, I am delighted to support our digital team’s idea of launching a quarterly digital newsletter—a platform that will keep us informed, connected, and prepared to lead in the telecommunications industry."
export {
    desc, DanielToran, AliAliZahid
}

